spring:
  datasource:
    url: jdbc:mysql://localhost:3307/movies
    username: user
    password: app_password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  file:
    name:
      logs/app.log
  level:
    org:
      org.springframework: debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace